#!/bin/sh
set -e

if command -v bash >/dev/null 2>&1; then
  bash scripts/check_main_py.sh
else
  echo "[pre-commit] bash not found in PATH." >&2
  exit 1
fi

if command -v python >/dev/null 2>&1; then
  python scripts/set_build_number.py --build-only
elif command -v py >/dev/null 2>&1; then
  py -3 scripts/set_build_number.py --build-only
else
  echo "[pre-commit] Python not found in PATH." >&2
  exit 1
fi

git add utils/_build.py
